//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cayan.Tool.SqlProjScanner.ConsoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleOutput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleOutput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cayan.Tool.SqlProjScanner.ConsoleApp.Resources.ConsoleOutput", typeof(ConsoleOutput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify create or compare.
        /// </summary>
        internal static string ArgumentInstruction {
            get {
                return ResourceManager.GetString("ArgumentInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide -data-file.
        /// </summary>
        internal static string DataFileError {
            get {
                return ResourceManager.GetString("DataFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter -help or -h for help.
        /// </summary>
        internal static string HelpInstruction {
            get {
                return ResourceManager.GetString("HelpInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ======= SQL SCANNER HELP ======
        ///
        ///Specify &apos;create&apos; argument to generate an xml data file
        ///Specify &apos;compare&apos; argument to compare to an xml data file and then generate an html report
        ///
        ///For create, specify the following arguments:
        ///-solution-path or -s, the path to SQL to project to be scanned
        ///-data-file or -d, path to the data file to be generated
        ///
        ///For compare, specify the following arguments: 
        ///-solution-path or -s, the path to SQL to project to be scanned
        ///-data-file or -d, path to the xml data file to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide -report.
        /// </summary>
        internal static string ReportError {
            get {
                return ResourceManager.GetString("ReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide -solution-path.
        /// </summary>
        internal static string SolutionPathError {
            get {
                return ResourceManager.GetString("SolutionPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time taken.
        /// </summary>
        internal static string TimeTakenMessage {
            get {
                return ResourceManager.GetString("TimeTakenMessage", resourceCulture);
            }
        }
    }
}
